name: CI/CD DEPLOYMENT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_STATIC_IP }} "echo 'SSH connection successful!'"

      - name: Build and Deploy
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.LIGHTSAIL_STATIC_IP }} << 'EOF'
          cd /home/ubuntu/noq_app_deployment

          cd noQ-Frontend
          echo "FETCHING FRONTEND SUBMODULE..."
          git fetch origin
          git stash push --include-untracked || true
          git reset --hard HEAD || true
          git checkout main
          git pull origin main

          echo "SETTING UP .env.prod..."
          if [ "$BUILD_MODE" = "prod" ]; then
            rm -f .env.prod
            echo "NOQ_OS_MOCK_API=false" > .env.prod
            echo "NOQ_BASE_URL=http://${{ secrets.LIGHTSAIL_STATIC_IP }}/" >> .env.prod
          fi

          cd ../noq_backend_python
          echo "FETCHING BACKEND SUBMODULE..."
          git fetch origin
          git stash push --include-untracked || true
          git reset --hard HEAD || true
          cd ..

          echo "HANDLING MAIN..."
          git fetch origin
          git stash push --include-untracked || true
          git reset --hard HEAD || true
          git checkout main
          git pull origin main

          echo "SUBMODULE INIT AND UPDATE..."
          git submodule init
          git submodule update

          echo "DOCKER OPERATIONS STARTING..."
          sudo docker-compose down
          sudo docker-compose build --no-cache
          sudo docker-compose up -d

          echo 'End of Deployment'
          EOF
